# Site settings
title: cosas en venta
email: pauvaliente@gmail.com
description: "En algún momento de la vida hay que vaciar la mochila. Este es mi momento y estas son las cosas de las que me desprendo."
baseurl: "/rastrillo"
url: "http://paucc.github.io"

# Build settings
markdown: kramdown
permalink: pretty
